# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-28 19:23
# Copyright 2023 Endless OS Foundation LLC
# SPDX-License-Identifier: GPL-2.0-or-later
from __future__ import unicode_literals

from django.db import migrations


def clear_language_id(apps, schema_editor):
    """Clear the device language to use the system language

    Set DeviceSettings.language_id to null so that the system language
    is used. Since the device settings have never been exposed, all
    existing devices are assumed to be using the old en default.
    """
    DeviceSettings = apps.get_model("device", "DeviceSettings")
    DeviceSettings.objects.update(language_id=None)


class Migration(migrations.Migration):

    dependencies = [
        # Requires the DeviceSettings.language_id field allowing null to
        # exist.
        ("device", "0004_auto_20190306_0553")
    ]

    operations = [
        migrations.RunPython(clear_language_id, migrations.RunPython.noop),
    ]
