# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-28 20:25
# Copyright 2023 Endless OS Foundation LLC
# SPDX-License-Identifier: GPL-2.0-or-later
from __future__ import unicode_literals

from django.db import migrations


def delete_admin_user(apps, schema_editor):
    """Delete the admin user created by automatic provisioning

    Since user management has never been exposed, assume any existing admin
    user was created automatically.
    """
    FacilityUser = apps.get_model("kolibriauth", "FacilityUser")
    FacilityUser.objects.filter(username="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("kolibri_tools.plugin", "0001_clear_language_id"),
        # Make sure the FacilityUser model exists.
        ("kolibriauth", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(delete_admin_user, migrations.RunPython.noop),
    ]
