name: CI

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      tag_name:
        description: 'The git tag name for release'
        default: ''
        required: true
        type: string
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        architecture: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: ${{ matrix.architecture }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install python requirements
        run: |
          pip install wheel

      - name: Checkout pyinstaller
        uses: actions/checkout@v3
        with:
          repository: pyinstaller/pyinstaller
          path: pyinstaller
          ref: v5.1

      - name: Build pyinstaller bootloader
        run: |
          if ("${{ matrix.architecture }}" -eq "x86") {
            python waf all --target-arch=32bit
          }
          else {
            python waf all
          }
        working-directory: pyinstaller/bootloader

      - name: Install pyinstaller
        run: |
          python setup.py install
        working-directory: pyinstaller
        env:
          PYINSTALLER_COMPILE_BOOTLOADER: 1

      - name: Prep kolibri dist
        env:
          KOLIBRI_WHL_URL: 'https://github.com/endlessm/kolibri-explore-plugin/releases/download/v5.8.0/kolibri-0.16.0.dev0+git.20220928203123-py2.py3-none-any.whl'
          KOLIBRI_WHL_FILENAME: "kolibri-0.16.0.dev0+git.20220928203123-py2.py3-none-any.whl"
        run: |
          C:\msys64\usr\bin\wget.exe -O $env:KOLIBRI_WHL_FILENAME $env:KOLIBRI_WHL_URL
          pip install $env:KOLIBRI_WHL_FILENAME --target="src"

      - name: Add kolibri_zim_plugin to Kolibri's dist packages
        run: |
          pip install kolibri-zim-plugin[full] --target="src\kolibri\dist"

      - name: Add kolibri_explore_plugin to Kolibri's dist packages
        run: |
          pip install kolibri-explore-plugin --target="src\kolibri\dist"

      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "endlessm/kolibri-explore-plugin"
          latest: true
          fileName: "apps-bundle.zip"

      - name: Add apps-bundle to Kolibri's dist packages
        run: |
          7z x apps-bundle.zip -osrc/apps-bundle

      - name: Download the collections manifest
        uses: actions/checkout@v3
        with:
          repository: endlessm/endless-key-collections
          path: collections

      - name: Add endless-key-collections to Kolibri's dist package
        run: |
          mv collections/json src/collections

      - name: Patch Kolibri
        run: |
          C:\msys64\usr\bin\patch.exe src\kolibri\core\content\tasks.py patches\0001-Add-track-progress-information-to-channelimport.patch

      - name: Build
        env:
          PYTHONOPTIMIZE: 2
        run: |
          # Precompile the py as pyc files
          python.exe -m compileall src\kolibri\ -b
          # Remove py source files, except the DB migrations https://github.com/endlessm/endless-key-app/pull/99
          Get-Childitem -Path src\kolibri\ -Include *.py -File -Recurse | where-object fullname -notlike "*\migrations\*.py" | Remove-Item -Force
          # Build as a Windows executable binary
          pyinstaller.exe --noconfirm main.spec
          # Remove the __pycache__
          Get-Childitem -Path src\kolibri\ -Include __pycache__ -Directory -Recurse | Remove-Item -Recurse -Force

      - name: Install electron-forge
        working-directory: kolibri-electron
        run: yarn global add @electron-forge/cli

      - name: Install electron dependencies
        working-directory: kolibri-electron
        run: yarn install

      - name: Build electron app
        working-directory: kolibri-electron
        run: |
          if ("${{ matrix.architecture }}" -eq "x86") {
            yarn make --arch=ia32
          }
          else {
            yarn make
          }

      - name: Kolibri cleanup
        run: |
          $KOLIBRI_MODULE_PATH = "src/kolibri"

          & ./cleanup-unused-locales.py -l `
          ${KOLIBRI_MODULE_PATH}/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/conf/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/admin/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/admindocs/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/auth/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/contenttypes/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/flatpages/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/gis/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/humanize/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/postgres/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/redirects/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/sessions/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django/contrib/sites/locale `
          ${KOLIBRI_MODULE_PATH}/dist/django_filters/locale `
          ${KOLIBRI_MODULE_PATH}/dist/mptt/locale `
          ${KOLIBRI_MODULE_PATH}/dist/rest_framework/locale

          rm -r -fo `
          ${KOLIBRI_MODULE_PATH}/dist/cext/cp27, `
          ${KOLIBRI_MODULE_PATH}/dist/cext/cp36, `
          ${KOLIBRI_MODULE_PATH}/dist/cext/cp38, `
          ${KOLIBRI_MODULE_PATH}/dist/cext/cp39, `
          ${KOLIBRI_MODULE_PATH}/dist/cext/*/*Linux*

          rm -r -fo `
          ${KOLIBRI_MODULE_PATH}/dist/cheroot/test, `
          ${KOLIBRI_MODULE_PATH}/dist/colorlog/tests, `
          ${KOLIBRI_MODULE_PATH}/dist/django_js_reverse/tests, `
          ${KOLIBRI_MODULE_PATH}/dist/future/backports/test, `
          ${KOLIBRI_MODULE_PATH}/dist/future/moves/test, `
          ${KOLIBRI_MODULE_PATH}/dist/ipware/tests, `
          ${KOLIBRI_MODULE_PATH}/dist/magicbus/test, `
          ${KOLIBRI_MODULE_PATH}/dist/more_itertools/tests, `
          ${KOLIBRI_MODULE_PATH}/dist/past/tests, `
          ${KOLIBRI_MODULE_PATH}/dist/py2only, `
          ${KOLIBRI_MODULE_PATH}/dist/sqlalchemy/testing

      - name: Create kolibri-windows
        run: |
          $ElectronDiretory = (Get-Childitem -Path kolibri-electron\out\ -Directory kolibri-electron-win32*)[0]
          mv $ElectronDiretory kolibri-windows

          mv src/kolibri dist/Kolibri/kolibri
          mv dist/Kolibri kolibri-windows/resources/app/src/
          mv src/apps-bundle kolibri-windows/resources/app/src/
          mv src/collections kolibri-windows/resources/app/src/

      - name: Compress
        run: Compress-Archive -Path kolibri-windows\* -DestinationPath kolibri-windows_${{ matrix.architecture }}.zip
        shell: pwsh

      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        with:
          name: "kolibri-windows_${{ matrix.architecture }}.zip"
          path: "kolibri-windows_${{ matrix.architecture }}.zip"


  package:
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Need to fetch everything so that 'git describe' can see the tags
          fetch-depth: 0

      - name: Download the kolibri-windows.zip
        uses: actions/download-artifact@v3
        with:
          name: kolibri-windows_${{ matrix.architecture }}.zip

      - name: Calculate version from repository
        if: (startsWith(github.ref, 'refs/tags/') == false) && (startsWith(inputs.tag_name, 'v') == false)
        run: |
          $describe = (git describe --always --tags --long --match 'v*')
          $ver_arr = $describe -split '[-v]'
          # Always ".0" to make it windows store compatible
          $ver_str = $ver_arr[1] + ".0"
          echo "BUILD_VERSION=$ver_str" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Using version from inputs
        if: startsWith(inputs.tag_name, 'v')
        run: |
          $ver_arr =  "$env:TAG_NAME" -split '[-v]'
          # Always ".0" to make it windows store compatible
          $ver_str = $ver_arr[1] + ".0"
          echo "BUILD_VERSION=$ver_str" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh
        env:
          TAG_NAME: ${{ inputs.tag_name }}

      - name: Using version from ref
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $ver_arr = ${Env:GITHUB_REF_NAME} -split '[-v]'
          # Always ".0" to make it windows store compatible
          $ver_str = $ver_arr[1] + ".0"
          echo "BUILD_VERSION=$ver_str" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - name: Packaging
        run: |
          Expand-Archive kolibri-windows_${{ matrix.architecture }}.zip -DestinationPath kolibri-windows

          echo "Set package's version as ${Env:BUILD_VERSION}"
          $src = "build_winapp/appxmanifest.xml"
          $dst = "kolibri-windows/appxmanifest.xml"

          # Set version and architecture in the manifest file
          $manifest = Get-Content $src
          $manifest -replace '1.0.0.0',$Env:BUILD_VERSION -replace 'x64','${{ matrix.architecture }}' > $dst

          Get-Content $dst

          Copy-Item -Path "build_winapp/assets" -Destination "kolibri-windows/" -recurse
          & "${Env:ProgramFiles(x86)}\Windows Kits\10\App Certification Kit\makeappx.exe" pack /d kolibri-windows /p endlesskey_${{ matrix.architecture }}.appx
        shell: pwsh

      - name: Upload unsigned package
        uses: actions/upload-artifact@v3
        with:
          name: "endlesskey_${{ matrix.architecture }}.appx"
          path: "endlesskey_${{ matrix.architecture }}.appx"

      - name: Sign artifact for testing
        id: sign_for_testing
        if: (startsWith(github.ref, 'refs/tags/') == false) && (startsWith(inputs.tag_name, 'v') == false)
        shell: pwsh
        env:
          SIGN_PHRASE: ${{ secrets.SELFSIGN_PHRASE }}
        run: |
          & "${Env:ProgramFiles(x86)}\Windows Kits\10\App Certification Kit\signtool.exe" `
            sign /fd SHA256 /a /f build_winapp/selfsign.pfx /p $env:SIGN_PHRASE endlesskey_${{ matrix.architecture }}.appx
          mv endlesskey_${{ matrix.architecture }}.appx endlesskey_${{ matrix.architecture }}.selfsigned.appx

      - name: Upload self-signed package for testing
        if: steps.sign_for_testing.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: "endlesskey_${{ matrix.architecture }}.selfsigned.appx"
          path: "endlesskey_${{ matrix.architecture }}.selfsigned.appx"


  sign_binaries_for_EK_USB_image:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || startsWith(inputs.tag_name, 'v')
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]

    steps:
      - name: Download the kolibri-windows.zip
        uses: actions/download-artifact@v3
        with:
          name: kolibri-windows_${{ matrix.architecture }}.zip

      - name: Sign the binaries
        id: sign_binaries
        shell: pwsh
        env:
          SIGNPATH_ORG_ID: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          SIGNPATH_USER_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
        run: |
          Expand-Archive kolibri-windows_${{ matrix.architecture }}.zip -DestinationPath kolibri-windows

          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -name SignPath
          Submit-SigningRequest `
            -CIUserToken $env:SIGNPATH_USER_TOKEN `
            -OrganizationId $env:SIGNPATH_ORG_ID `
            -ProjectSlug Endless_Apps `
            -SigningPolicySlug Endless_Apps_Signing_for_Endless_USB_Key `
            -ArtifactConfigurationSlug Binaries_for_Endless_USB_Key `
            -InputArtifactPath kolibri-windows/kolibri-electron.exe `
            -OutputArtifactPath kolibri-electron.signed.exe `
            -WaitForCompletion

          Submit-SigningRequest `
            -CIUserToken $env:SIGNPATH_USER_TOKEN `
            -OrganizationId $env:SIGNPATH_ORG_ID `
            -ProjectSlug Endless_Apps `
            -SigningPolicySlug Endless_Apps_Signing_for_Endless_USB_Key `
            -ArtifactConfigurationSlug Binaries_for_Endless_USB_Key `
            -InputArtifactPath kolibri-windows/resources/app/src/Kolibri/Kolibri.exe `
            -OutputArtifactPath Kolibri.signed.exe `
            -WaitForCompletion

          rm kolibri-windows/kolibri-electron.exe
          rm kolibri-windows/resources/app/src/Kolibri/Kolibri.exe
          mv kolibri-electron.signed.exe kolibri-windows/kolibri-electron.exe
          mv Kolibri.signed.exe kolibri-windows/resources/app/src/Kolibri/Kolibri.exe

          rm kolibri-windows_${{ matrix.architecture }}.zip

      - name: Compress
        run: Compress-Archive -Path kolibri-windows\* -DestinationPath kolibri-windows_${{ matrix.architecture }}.zip
        shell: pwsh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.sign_binaries.outcome == 'success'
        with:
          files: kolibri-windows_${{ matrix.architecture }}.zip
          tag_name: ${{ inputs.tag_name }}

  push_to_MS_store:
    needs: package
    if: startsWith(github.ref, 'refs/tags/') || startsWith(inputs.tag_name, 'v')
    runs-on: windows-2019

    steps:
      - name: Download the package
        uses: actions/download-artifact@v3

      - name: Gather the package files
        run: |
          mkdir packages

          $packages = Get-Childitem -Path .\ -Include *.appx -Exclude *selfsigned* -File -Recurse
          mv $packages packages/

      - name: Checkout StoreBroker
        uses: actions/checkout@v3
        with:
          repository: microsoft/StoreBroker
          path: StoreBroker

      - name: Create and push the Application Payload to Package Flight on Microsoft store
        shell: pwsh
        env:
          MS_TENANT_ID: ${{ secrets.MSPARTNER_TENANTID }}
          MS_CLIENT_ID: ${{ secrets.MSPARTNER_CLIENTID }}
          MS_CLIENT_PWD: ${{ secrets.MSPARTNER_CLIENTPWD }}
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name StoreBroker

          $APP_ID = "9PDLJFW5D4JR"
          $SubmissionRoot = "MSSubmission"

          $PWD = ConvertTo-SecureString $env:MS_CLIENT_PWD -AsPlainText -Force
          $Credentials = New-Object System.Management.Automation.PSCredential ($env:MS_CLIENT_ID, $PWD)
          Set-StoreBrokerAuthentication -TenantId $env:MS_TENANT_ID -Credential $Credentials -Verbose

          New-Item -Path "MSAppPayload" -ItemType Directory

          # Get current config and PDPs from Microsoft store
          New-StoreBrokerConfigFile -Path "MSAppPayload/SBConfig.json" -AppId $APP_ID
          $release_str = Get-Date -Format "yyyyMMdd"
          .\StoreBroker\Extensions\ConvertFrom-ExistingSubmission.ps1 -AppId $APP_ID -Release $release_str -OutPath "MSAppPayload/PDPs"

          # Wipe out the Release string in PDP.xml to avoid the release version folder
          [xml]$xmlDoc = Get-Content "MSAppPayload/PDPs/en-us/PDP.xml"
          $xmlDoc.ProductDescription.Release = ""
          $xmlDoc.Save( "MSAppPayload/PDPs/en-us/PDP.xml" )

          echo "Going to create dummy screenshots for Application Payload creation:"
          $xmlDoc.ProductDescription.ScreenshotCaptions.Caption | ForEach-Object {
            $dummy_screenshot = "MSAppPayload/PDPs/en-us/" + $_.DesktopImage
            echo $dummy_screenshot
            echo NULL > $dummy_screenshot
          }

          New-SubmissionPackage `
            -ConfigPath "MSAppPayload/SBConfig.json" `
            -PDPRootPath "MSAppPayload/PDPs" `
            -ImagesRootPath "MSAppPayload/PDPs" `
            -AppxPath packages/*.appx `
            -MediaFallbackLanguage en-US `
            -OutPath $SubmissionRoot `
            -OutName endlesskey `
            -Verbose

          $FLIGHT_NAME = "Alpha Test Flight"
          $flight = Get-ApplicationFlights -AppId $APP_ID | Where-Object { $_.friendlyName -eq $FLIGHT_NAME }

          Update-ApplicationFlightSubmission `
            -AppId $APP_ID `
            -FlightId $flight.flightId `
            -SubmissionDataPath "$SubmissionRoot/endlesskey.json" `
            -PackagePath "$SubmissionRoot/endlesskey.zip" `
            -ReplacePackages `
            -AutoCommit `
            -Force `
            -Verbose
