name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install xapian-core
        run: |
          C:\msys64\usr\bin\pacman.exe --verbose --noconfirm -S mingw-w64-x86_64-xapian-core

      # - name: Download Xapian
      #   run: |
      #     cd src
      #     Invoke-WebRequest 'https://oligarchy.co.uk/xapian/1.4.18/xapian-core-1.4.18.tar.xz' -outfile xapian-core-1.4.18.tar.xz
      #     Extract-7Zip xapian-core-1.4.18.tar.xz .
      #     Extract-7Zip xapian-core-1.4.18.tar .
      #     ls
      #     mv xapian-core-1.4.18 xapian-core

      # - name: Install zlib
      #   run: |
      #     powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat

      # - name: Prepare MSVC
      #   uses: bus1/cabuild/action/msdevshell@v1
      #   with:
      #     architecture: x64

      # - name: Build Xapian
      #   shell: bash
      #   run: |
      #     cd src/xapian-core
      #     ./configure CC="cl -nologo" CXX="$PWD/compile cl -nologo" CXXFLAGS="-EHsc -MD" AR=lib CPPFLAGS="-IC:/Program\ Files/zlib/include" LDFLAGS="-LC:/Program\ Files/zlib/lib" --disable-backend-remote --disable-documentation
      #     make
      #     make install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install requirements
        run: |
          $env:Path += ";C:\msys64\usr\bin"
          $env:Path += ";C:\msys64\mingw64\bin"
          pip install wheel
          pip install -r requirements.txt
          pip install -r requirements-win.txt
          npm install -g yarn
          yarn global add @electron-forge/cli

      - name: Prep kolibri dist
        run: |
          python kapew.py prep-kolibri-dist --exclude-prereleases --skip-preseed

      - name: Update kolibri.dist.le_utils for kolibri-zim-plugin
        run: |
          pip install git+https://github.com/learningequality/le-utils.git@master --target="src\kolibri\dist" --upgrade

      - name: Update kolibri.dist.morango for improved performance on Windows
        run: |
          pip install morango==0.5.6 --target="src\kolibri\dist" --upgrade

      - name: Add kolibri_zim_plugin to Kolibri's dist packages
        run: |
          pip install kolibri-zim-plugin --target="src\kolibri\dist"

      # - name: Apply performance patches
      #   run: |
      #     cp patches/morango-models-utils.py src/kolibri/dist/morango/models/utils.py

      - name: Build
        run: |
          $env:Path += ";C:\msys64\usr\bin"
          $env:Path += ";C:\msys64\mingw64\bin"
          python kapew.py build

      - name: Add package data files to dist
        run: |
          mv src/kolibri dist/win/Kolibri
          mv dist/win/Kolibri kolibri-electron/src/

      - name: Install electron dependencies
        working-directory: kolibri-electron
        run: |
          yarn install
          yarn make

      - name: Create kolibri-windows
        run: |
          mv kolibri-electron/out/kolibri-electron-win32-x64 kolibri-windows

      - uses: actions/upload-artifact@v2
        with:
          name: "kolibri-windows"
          path: "kolibri-windows"
